services:
  server:
    container_name: ${NFCGATESERVER_SERVICE_HOST}
    build:
      context: ../src
      dockerfile: ../docker/nfcgate_server.Dockerfile
    env_file: ../.env
    expose: ["${NFCGATESERVER_PORT}"]
  gateway:
    build:
      context: ../gateway
      dockerfile: ../docker/gateway.Dockerfile
    container_name: ${GATEWAY_SERVICE_HOST}
    depends_on: [server]
    environment:
      - PROJECT_NAME=${PROJECT_NAME}
      - PROJECT_DOMAIN=${PROJECT_DOMAIN}
      - NFCGATESERVER_DOMAIN=${NFCGATESERVER_DOMAIN}
      - NFCGATESERVER_SERVICE_HOST=${NFCGATESERVER_SERVICE_HOST}
      - NFCGATESERVER_PORT=${NFCGATESERVER_PORT}
    ports: ["${NFCGATESERVER_PORT}:${NFCGATESERVER_PORT}"]
    volumes: ["gateway_config:/etc/nginx", "certs:/etc/nginx/certs"]

volumes:
  certs:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ../gateway/config/certs
  gateway_config:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ../gateway/config
