services:
  nfcgate_server:
    container_name: ${NFCGATESERVER_SERVICE_HOST}
    build:
      context: ../services/nfcgate_server/src
      dockerfile: ../../../docker/nfcgate_server.Dockerfile
    env_file: ../.env
    volumes: ["certs:/usr/src/app/certs"]
    command: ["--verify"]
    expose: ["${NFCGATESERVER_PORT}"]

  httptest_server:
    container_name: ${TESTHTTP_SERVICE_HOST}
    build:
      context: ../services/httptest_server/src
      dockerfile: ../../../docker/httptest_server.Dockerfile
    env_file: ../.env
    expose: ["${TESTHTTP_PORT}"]

  gateway:
    depends_on:
      - nfcgate_server
      - httptest_server
      - cert-manager
    build:
      context: ../gateway
      dockerfile: ../docker/gateway.Dockerfile
    container_name: ${GATEWAY_SERVICE_HOST}
    environment:
      - PROJECT_NAME=${PROJECT_NAME}
      - PROJECT_DOMAIN=${PROJECT_DOMAIN}
      - NFCGATESERVER_DOMAIN=${NFCGATESERVER_DOMAIN}
      - NFCGATESERVER_SERVICE_HOST=${NFCGATESERVER_SERVICE_HOST}
      - NFCGATESERVER_PORT=${NFCGATESERVER_PORT}
      - TESTHTTP_SERVICE_HOST=${TESTHTTP_SERVICE_HOST}
      - TESTHTTP_PORT=${TESTHTTP_PORT}
      - TESTHTTP_DOMAIN=${TESTHTTP_DOMAIN}
    ports:
      [
        "${NFCGATESERVER_PORT}:${NFCGATESERVER_PORT}",
        "${TESTHTTP_PORT}:${TESTHTTP_PORT}",
      ]
    volumes: ["gateway_config:/etc/nginx", "certs:/etc/nginx/certs"]

  cert-manager:
    container_name: ${CERT_MANAGER_HOST_SERVICE}
    image: jacoelho/generate-certificate
    volumes: ["certs:/certificates"]
    environment:
      - SERVER=${PROJECT_DOMAIN}

volumes:
  certs:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ../gateway/config/certs
  gateway_config:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ../gateway/config
