# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: c2c.proto
# Protobuf Python Version: 5.27.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    27,
    1,
    '',
    'c2c.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\tc2c.proto\x12*de.tu_darmstadt.seemoo.nfcgate.network.c2c\"\x9f\x02\n\x07NFCData\x12S\n\x0b\x64\x61ta_source\x18\x01 \x01(\x0e\x32>.de.tu_darmstadt.seemoo.nfcgate.network.c2c.NFCData.DataSource\x12O\n\tdata_type\x18\x02 \x01(\x0e\x32<.de.tu_darmstadt.seemoo.nfcgate.network.c2c.NFCData.DataType\x12\x11\n\ttimestamp\x18\x04 \x01(\x03\x12\x0c\n\x04\x64\x61ta\x18\x03 \x01(\x0c\"\"\n\nDataSource\x12\n\n\x06READER\x10\x00\x12\x08\n\x04\x43\x41RD\x10\x01\")\n\x08\x44\x61taType\x12\x0b\n\x07INITIAL\x10\x00\x12\x10\n\x0c\x43ONTINUATION\x10\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'c2c_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_NFCDATA']._serialized_start=58
  _globals['_NFCDATA']._serialized_end=345
  _globals['_NFCDATA_DATASOURCE']._serialized_start=268
  _globals['_NFCDATA_DATASOURCE']._serialized_end=302
  _globals['_NFCDATA_DATATYPE']._serialized_start=304
  _globals['_NFCDATA_DATATYPE']._serialized_end=345
# @@protoc_insertion_point(module_scope)
